-- =============================================================
-- 0004_exam.sql — exam engine (classic + CAT/adaptive)
-- Tables: exam_sessions, exam_results, exam_progress
--
-- Derived from models/exam.go + repository/exam_repo.go.
-- exam_sessions is a SINGLE table shared by classic sessions and
-- CAT sessions (cat_mode / theta_* / start_theta columns; see
-- ExamRepository.CreateCatSession). ids are DB-generated
-- (RETURNING id) — identity columns, semantically equal to the
-- serial-style sequences used previously.
--
-- Deliberate omission: exam_results.session_id has NO foreign key
-- to exam_sessions — CAT results are inserted with NULL session_id
-- (CreateCatResult) and classic results reference it loosely.
-- =============================================================

CREATE TABLE IF NOT EXISTS exam_sessions (
    id                    integer     GENERATED BY DEFAULT AS IDENTITY,
    user_id               text        NOT NULL,
    exam_type             text        NOT NULL,  -- hsk|tocfl|goethe|jlpt|toefl
    exam_level            text        NOT NULL,
    status                text        NOT NULL DEFAULT 'in_progress',  -- in_progress | completed | abandoned
    current_question_index integer    NOT NULL DEFAULT 0,
    questions             jsonb,
    answers               jsonb,
    started_at            timestamptz NOT NULL DEFAULT now(),
    completed_at          timestamptz,
    time_limit            integer,
    time_remaining        integer,
    question_count        integer     NOT NULL DEFAULT 0,
    question_types        jsonb,
    difficulty_range      jsonb,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    -- CAT-only columns:
    cat_mode              boolean     NOT NULL DEFAULT false,
    theta_estim           double precision,
    theta_sd              double precision,
    engine_version        text,
    start_theta           double precision,
    last_answer_at        timestamptz,
    CONSTRAINT exam_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT exam_sessions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);

-- GetActiveSessions: WHERE user_id AND status='in_progress'
CREATE INDEX IF NOT EXISTS idx_exam_user ON exam_sessions (user_id, status);

CREATE TABLE IF NOT EXISTS exam_results (
    id                       integer     GENERATED BY DEFAULT AS IDENTITY,
    session_id               integer,    -- nullable: CAT results have no session row
    user_id                  text        NOT NULL,
    exam_type                text        NOT NULL,
    exam_level               text        NOT NULL,
    total_questions          integer     NOT NULL DEFAULT 0,
    correct_answers          integer     NOT NULL DEFAULT 0,
    score                    integer     NOT NULL DEFAULT 0,
    passing_score            integer     NOT NULL DEFAULT 60,
    by_question_type         jsonb,
    by_difficulty            jsonb,
    time_taken               integer     NOT NULL DEFAULT 0,
    average_time_per_question integer    NOT NULL DEFAULT 0,
    recommended_next_level   text,
    weak_areas               jsonb,
    strengths                jsonb,
    created_at               timestamptz NOT NULL DEFAULT now(),
    -- CAT-only columns:
    cefr_band                text,
    elo_estimate             double precision,  -- NULL ⇒ classic result (GetCatProgress filter)
    elo_sd                   double precision,
    integrity_flag           boolean     NOT NULL DEFAULT false,
    answers                  jsonb,
    engine_version           text,
    CONSTRAINT exam_results_pkey PRIMARY KEY (id),
    CONSTRAINT exam_results_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_examresult_user ON exam_results (user_id);

-- Per-user per-exam aggregate. PK = upsert target of UpsertExamProgress.
CREATE TABLE IF NOT EXISTS exam_progress (
    user_id               text        NOT NULL,
    exam_type             text        NOT NULL,
    levels_completed      jsonb,
    current_level         text,
    highest_score         integer     NOT NULL DEFAULT 0,
    average_score         integer     NOT NULL DEFAULT 0,
    total_attempts        integer     NOT NULL DEFAULT 0,
    by_level              jsonb,
    weak_question_types   jsonb,
    weak_difficulty_levels jsonb,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT exam_progress_pkey PRIMARY KEY (user_id, exam_type),
    CONSTRAINT exam_progress_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);
