-- =============================================================
-- 0006_supporter.sql — donation supporters wall
-- Tables: supporter
--
-- Derived from models/supporter.go + repository/supporter_repo.go.
-- Upsert targets ON CONFLICT (external_id); platform set is the
-- two payment integrations wired in handler/supporter_handler.go.
-- =============================================================

CREATE TABLE IF NOT EXISTS supporter (
    id          integer     GENERATED BY DEFAULT AS IDENTITY,
    name        text        NOT NULL DEFAULT 'Anonymous',
    avatar_url  text,
    platform    text        NOT NULL,
    amount      numeric,    -- hidden from public API; admin-only
    message     text,
    is_public   boolean     NOT NULL DEFAULT true,
    external_id text        NOT NULL,  -- provider transaction id
    donated_at  timestamptz NOT NULL DEFAULT now(),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT supporter_pkey PRIMARY KEY (id),
    CONSTRAINT supporter_external_id_key UNIQUE (external_id),
    CONSTRAINT supporter_platform_check CHECK (platform IN ('kofi', 'trakteer'))
);

-- ListPublic: WHERE is_public ORDER BY donated_at DESC
CREATE INDEX IF NOT EXISTS idx_supporter_public_donated ON supporter (is_public, donated_at DESC);
